### ISSUE TITLE
Unable to pip install it. Everytime I keep getting the error below 

### ISSUE THREAD

**Issue by adityabharadwaj14** [BSchilperoort/thermalpy#1]
WARNING: The directory '/home/aditya/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://github.com/BSchilperoort/thermalpy/zipball/master
  Downloading https://github.com/BSchilperoort/thermalpy/zipball/master
     - 7.2 kB 26 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ezu9iyb6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ezu9iyb6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-ezu9iyb6/pip-egg-info
         cwd: /tmp/pip-req-build-ezu9iyb6/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-ezu9iyb6/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by BSchilperoort** [comment]
It looks like the error is not related to the library itself. However, I have not tested pip either.

If you want to use the code, just download the source and import it directly. Be aware that the Spinnaker library often changes, so you might not be able to use it. You will need to install both Spinnaker and PySpin from FLIR's repository.
